"""Shared constants for GPX workflows."""

FOLDER_META_TIME_SHIFT = "TIME_SHIFT"
NOT_SET_TIME_SHIFT_LABEL = "NOT SET"
DEFAULT_GPX_TOLERANCE_SECONDS = 10
KML_THUMBNAIL_SIZE = 350

APPLY_MODE_ONLY_KML = "ONLY_KML"
APPLY_MODE_UPDATE_DB = "UPDATE_DB"
