"""Shared constants for GPX workflows."""

FOLDER_STATE_LAST_TIME_SHIFT = "TIME_SHIFT"
FOLDER_STATE_LAST_GPX_PATH = "GPX_PATH"
NOT_SET_TIME_SHIFT_LABEL = "NOT SET"
DEFAULT_GPX_TOLERANCE_SECONDS = 10
KML_THUMBNAIL_SIZE = 350
