"""Autogenerated settings dialog driven by schema descriptors."""

from __future__ import annotations

from functools import partial
import os

from PySide6.QtCore import Signal
from PySide6.QtWidgets import (
    QDialog,
    QDialogButtonBox,
    QFormLayout,
    QGroupBox,
    QMessageBox,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)

from ..settings_state import (
    RuntimeSettingKey,
    SettingsPanelSaveMode,
    UserSettingKey,
    get_runtime_setting,
    get_user_setting,
    set_user_setting,
)
from .editors import BaseEditor, build_editor
from .schema import SETTINGS_TABS, EditorKind, FieldSpec


class SettingsDialog(QDialog):
    setting_saved = Signal(object)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Settings")
        self.resize(850, 620)

        self._editors: dict[UserSettingKey, BaseEditor] = {}
        self._fields: dict[UserSettingKey, FieldSpec] = {}
        self._initial_values: dict[UserSettingKey, object] = {}
        self._changed_keys: set[UserSettingKey] = set()
        self._loading = False
        self._dirty = False

        self._mode = get_runtime_setting(RuntimeSettingKey.SETTINGS_PANEL_SAVE_MODE)

        self._build_ui()
        self._load_initial_values()

    @property
    def changed_keys(self) -> set[UserSettingKey]:
        return set(self._changed_keys)

    def _build_ui(self):
        root = QVBoxLayout(self)

        tabs = QTabWidget(self)
        root.addWidget(tabs)

        for tab_spec in SETTINGS_TABS:
            tab = QWidget(self)
            tab_layout = QVBoxLayout(tab)

            for group_spec in tab_spec.groups:
                group_box = QGroupBox(group_spec.title, tab)
                group_layout = QFormLayout(group_box)

                for field in group_spec.fields:
                    editor = build_editor(
                        field.editor,
                        choices=field.choices,
                        min_value=field.min_value,
                        max_value=field.max_value,
                    )
                    self._editors[field.key] = editor
                    self._fields[field.key] = field
                    group_layout.addRow(field.label, editor)

                    if self._mode == SettingsPanelSaveMode.AUTOSAVE:
                        editor.value_changed.connect(
                            partial(self._autosave_field, field.key)
                        )
                    else:
                        editor.value_changed.connect(self._on_field_changed)

                tab_layout.addWidget(group_box)

            tab_layout.addStretch(1)
            tabs.addTab(tab, tab_spec.title)

        if self._mode == SettingsPanelSaveMode.AUTOSAVE:
            buttons = QDialogButtonBox(QDialogButtonBox.StandardButton.Close)
            buttons.rejected.connect(self.reject)
            buttons.accepted.connect(self.accept)
            root.addWidget(buttons)
            return

        buttons = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Save
            | QDialogButtonBox.StandardButton.Cancel
        )
        buttons.accepted.connect(self._on_save)
        buttons.rejected.connect(self._on_cancel)
        root.addWidget(buttons)

    def _load_initial_values(self):
        self._loading = True
        try:
            for key, editor in self._editors.items():
                value = get_user_setting(key)
                editor.set_value(value)
                self._initial_values[key] = value
        finally:
            self._loading = False

    def _on_field_changed(self):
        if self._loading:
            return
        self._dirty = self._compute_dirty()

    def _compute_dirty(self) -> bool:
        for key, editor in self._editors.items():
            if editor.get_value() != self._initial_values.get(key):
                return True
        return False

    def _validate_field(self, key: UserSettingKey, value: object) -> bool:
        field = self._fields[key]
        if field.editor == EditorKind.PATH_DIR:
            if value and not os.path.isdir(str(value)):
                QMessageBox.warning(
                    self,
                    "Invalid Directory",
                    f"The directory does not exist:\n{value}",
                )
                return False
        if field.editor == EditorKind.PATH_FILE:
            if value and not os.path.isfile(str(value)):
                QMessageBox.warning(
                    self,
                    "Invalid File",
                    f"The file does not exist:\n{value}",
                )
                return False
        return True

    def _autosave_field(self, key: UserSettingKey):
        if self._loading:
            return

        editor = self._editors[key]
        value = editor.get_value()
        if not self._validate_field(key, value):
            editor.set_value(self._initial_values.get(key))
            return

        if value == self._initial_values.get(key):
            return

        set_user_setting(key, value)
        self._initial_values[key] = value
        self._changed_keys.add(key)
        self.setting_saved.emit(key)

    def _on_save(self):
        changed: dict[UserSettingKey, object] = {}

        for key, editor in self._editors.items():
            value = editor.get_value()
            if value == self._initial_values.get(key):
                continue
            if not self._validate_field(key, value):
                return
            changed[key] = value

        for key, value in changed.items():
            set_user_setting(key, value)
            self._initial_values[key] = value
            self._changed_keys.add(key)
            self.setting_saved.emit(key)

        self._dirty = False
        self.accept()

    def _on_cancel(self):
        if self._dirty:
            answer = QMessageBox.question(
                self,
                "Discard changes",
                "Some settings have changed. Discard them?",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No,
            )
            if answer != QMessageBox.StandardButton.Yes:
                return

        self.reject()
