"""Autogenerated settings dialog driven by schema descriptors."""

from __future__ import annotations

from functools import partial
import os

from PySide6.QtCore import QEvent, Qt, QTimer, Signal
from PySide6.QtGui import QColor, QPalette, QPixmap
from PySide6.QtWidgets import (
    QAbstractSpinBox,
    QDialogButtonBox,
    QFrame,
    QGridLayout,
    QGroupBox,
    QLabel,
    QLineEdit,
    QMessageBox,
    QScrollArea,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)

from piqopiqo.dialogs.unsaved_changes_dialog import UnsavedChangesDialog
from piqopiqo.model import TimeShiftOcrProvider
from piqopiqo.ssf.settings_state import (
    MandatorySettingInputKind,
    RuntimeSettingKey,
    SettingsPanelSaveMode,
    UserSettingKey,
    get_mandatory_setting_spec,
    get_runtime_setting,
    get_user_setting,
    set_user_setting,
    validate_mandatory_setting_value,
)

from .editors import BaseEditor, build_editor
from .schema import SETTINGS_TABS, EditorKind, FieldSpec

_GCP_OCR_FIELD_KEYS = {
    UserSettingKey.GCP_PROJECT,
    UserSettingKey.GCP_SA_KEY_PATH,
}

_TOP_ALIGNED_EDITOR_KINDS = {
    EditorKind.LIST_TEXT,
    EditorKind.MANUAL_LENSES,
    EditorKind.SHORTCUTS,
    EditorKind.STATUS_LABELS,
}
_SETTINGS_SECTION_SPACING = 4
_SETTINGS_PAGE_MARGIN_LEFT = 8
_SETTINGS_PAGE_MARGIN_RIGHT = 8


def _settings_form_row_spacing() -> int:
    return max(
        0,
        int(get_runtime_setting(RuntimeSettingKey.SETTINGS_PANEL_ROW_SPACING)),
    )


def _natural_height(widget: QWidget) -> int:
    return max(widget.sizeHint().height(), widget.minimumSizeHint().height())


def _use_background_color(widget: QWidget, color: QColor) -> None:
    palette = widget.palette()
    palette.setColor(QPalette.ColorRole.Window, color)
    widget.setPalette(palette)
    widget.setAutoFillBackground(True)


def _native_group_box_background_color(source: QWidget) -> QColor:
    sample = QGroupBox()
    sample.setPalette(source.palette())
    sample.resize(32, 32)
    pixmap = QPixmap(sample.size())
    pixmap.fill(source.palette().color(QPalette.ColorRole.Window))
    sample.render(pixmap)
    return pixmap.toImage().pixelColor(16, 16)


class _SettingsFormLayout(QGridLayout):
    """Form layout with equal visible label rhythm across mixed-height rows."""

    def __init__(self, *, row_spacing: int, parent: QWidget):
        super().__init__(parent)
        self._row_spacing = max(0, int(row_spacing))
        self._minimum_center_delta = 0
        self._rows: list[tuple[int, QLabel, QWidget, Qt.AlignmentFlag]] = []
        self._next_row = 0
        self.setProperty("settingsPanelRowSpacing", self._row_spacing)
        self.setColumnStretch(1, 1)
        self.setHorizontalSpacing(8)
        self.setVerticalSpacing(0)

    def add_subgroup_title(self, title: str) -> None:
        label = QLabel(str(title), self.parentWidget())
        label.setStyleSheet("font-weight: 600;")
        content_row = self._next_row
        self.addWidget(
            label,
            content_row,
            0,
            1,
            2,
            alignment=Qt.AlignmentFlag.AlignLeft,
        )
        self._rows.append((content_row, label, label, Qt.AlignmentFlag.AlignVCenter))
        self._next_row = content_row + 2
        self._update_gap_rows()

    def add_settings_row(
        self,
        label: QLabel,
        editor: QWidget,
        *,
        vertical_alignment: Qt.AlignmentFlag,
    ) -> None:
        content_row = self._next_row
        alignment = Qt.AlignmentFlag.AlignLeft | vertical_alignment
        label.setAlignment(alignment)
        self.addWidget(
            label,
            content_row,
            0,
            alignment=alignment,
        )
        self.addWidget(editor, content_row, 1)
        self._rows.append((content_row, label, editor, vertical_alignment))
        self._next_row = content_row + 2
        self._update_gap_rows()

    def setGeometry(self, rect) -> None:  # noqa: N802
        self._update_gap_rows()
        super().setGeometry(rect)

    def minimum_natural_center_delta(self) -> int:
        if len(self._rows) < 2:
            return 0

        row_heights = [
            max(_natural_height(label), _natural_height(editor))
            for _row, label, editor, _alignment in self._rows
        ]
        return max(
            (
                (previous + current + 1) // 2
                for previous, current, previous_row, current_row in zip(
                    row_heights[:-1],
                    row_heights[1:],
                    self._rows[:-1],
                    self._rows[1:],
                    strict=True,
                )
                if current_row[0] == previous_row[0] + 2
                and previous_row[3] == current_row[3] == Qt.AlignmentFlag.AlignVCenter
            ),
            default=0,
        )

    def centered_row_count(self) -> int:
        return sum(
            1
            for _row, _label, _editor, alignment in self._rows
            if alignment == Qt.AlignmentFlag.AlignVCenter
        )

    def set_minimum_center_delta(self, value: int) -> None:
        self._minimum_center_delta = max(0, int(value))
        self._update_gap_rows()

    def _update_gap_rows(self) -> None:
        if len(self._rows) < 2:
            return

        row_heights = [
            max(_natural_height(label), _natural_height(editor))
            for _row, label, editor, _alignment in self._rows
        ]
        minimum_center_delta = max(
            self._minimum_center_delta,
            self.minimum_natural_center_delta(),
        )
        target_center_delta = minimum_center_delta + self._row_spacing

        for previous, current, previous_row, current_row in zip(
            row_heights[:-1],
            row_heights[1:],
            self._rows[:-1],
            self._rows[1:],
            strict=True,
        ):
            if current_row[0] != previous_row[0] + 2:
                continue

            gap_row = previous_row[0] + 1
            if previous_row[3] != current_row[3]:
                self.setRowMinimumHeight(gap_row, self._row_spacing)
                continue
            if current_row[3] == Qt.AlignmentFlag.AlignTop:
                self.setRowMinimumHeight(gap_row, self._row_spacing)
                continue

            natural_center_delta = (previous + current + 1) // 2
            self.setRowMinimumHeight(
                gap_row,
                max(0, target_center_delta - natural_center_delta),
            )


def _harmonize_form_row_spacing(layouts: list[_SettingsFormLayout]) -> None:
    # Do not let short path-only sections dictate the rhythm of dense forms.
    dense_layouts = [layout for layout in layouts if layout.centered_row_count() >= 3]
    candidate_layouts = dense_layouts or layouts
    minimum_center_delta = max(
        (layout.minimum_natural_center_delta() for layout in candidate_layouts),
        default=0,
    )
    for layout in layouts:
        layout.set_minimum_center_delta(minimum_center_delta)


class _SettingsSection(QWidget):
    def __init__(self, title: str, parent: QWidget):
        super().__init__(parent)
        self.setProperty("settingsPanelSectionTitle", title)

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(_SETTINGS_SECTION_SPACING)

        self.title_label = QLabel(title, self)
        self.title_label.setProperty("settingsPanelSectionTitle", title)
        layout.addWidget(self.title_label)

        self.panel = QGroupBox(self)
        self.panel.setProperty("settingsPanelSectionTitle", title)
        layout.addWidget(self.panel)


def _settings_label_vertical_alignment(field: FieldSpec) -> Qt.AlignmentFlag:
    if field.editor in _TOP_ALIGNED_EDITOR_KINDS:
        return Qt.AlignmentFlag.AlignTop
    return Qt.AlignmentFlag.AlignVCenter


class SettingsDialog(UnsavedChangesDialog):
    setting_saved = Signal(object)

    def __init__(self, parent=None, initial_tab_title: str | None = None):
        super().__init__(parent)
        self.setWindowTitle("Settings")
        self.resize(850, 620)

        self._editors: dict[UserSettingKey, BaseEditor] = {}
        self._fields: dict[UserSettingKey, FieldSpec] = {}
        self._initial_values: dict[UserSettingKey, object] = {}
        self._changed_keys: set[UserSettingKey] = set()
        self._loading = False
        self._dirty = False
        self._tabs: QTabWidget | None = None
        self._initial_tab_title = str(initial_tab_title or "").strip()
        self._initial_focus_cleared = False

        self._mode = get_runtime_setting(RuntimeSettingKey.SETTINGS_PANEL_SAVE_MODE)

        self._build_ui()
        self._wire_editor_dependencies()
        self._install_line_edit_filters()
        self._load_initial_values()

    @property
    def changed_keys(self) -> set[UserSettingKey]:
        return set(self._changed_keys)

    def _build_ui(self):
        root = QVBoxLayout(self)

        self._tabs = QTabWidget(self)
        self._tabs.currentChanged.connect(self._on_tab_changed)
        root.addWidget(self._tabs)

        row_spacing = _settings_form_row_spacing()
        page_background = _native_group_box_background_color(self)
        for tab_spec in SETTINGS_TABS:
            tab_form_layouts: list[_SettingsFormLayout] = []
            tab_scroll = QScrollArea(self._tabs)
            tab_scroll.setFrameShape(QFrame.Shape.NoFrame)
            tab_scroll.setWidgetResizable(True)
            tab_scroll.setHorizontalScrollBarPolicy(
                Qt.ScrollBarPolicy.ScrollBarAlwaysOff
            )
            tab_scroll.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
            _use_background_color(tab_scroll.viewport(), page_background)

            tab_content = QWidget(tab_scroll)
            _use_background_color(tab_content, page_background)
            tab_layout = QVBoxLayout(tab_content)
            tab_layout.setContentsMargins(
                _SETTINGS_PAGE_MARGIN_LEFT,
                0,
                _SETTINGS_PAGE_MARGIN_RIGHT,
                0,
            )
            tab_layout.setSpacing(_SETTINGS_SECTION_SPACING)

            for group_spec in tab_spec.groups:
                visible_fields = [
                    field
                    for field in group_spec.fields
                    if self._should_include_field(field)
                ]
                if not visible_fields:
                    continue

                section = _SettingsSection(group_spec.title, tab_content)
                group_layout = _SettingsFormLayout(
                    row_spacing=row_spacing,
                    parent=section.panel,
                )
                tab_form_layouts.append(group_layout)

                current_subgroup: str | None = None
                for field in visible_fields:
                    subgroup = str(field.subgroup or "").strip()
                    if subgroup and subgroup != current_subgroup:
                        group_layout.add_subgroup_title(subgroup)
                        current_subgroup = subgroup
                    elif not subgroup:
                        current_subgroup = None

                    editor = build_editor(
                        field.editor,
                        choices=field.choices,
                        min_value=field.min_value,
                        max_value=field.max_value,
                    )
                    self._editors[field.key] = editor
                    self._fields[field.key] = field

                    label = QLabel(field.label, section.panel)
                    group_layout.add_settings_row(
                        label,
                        editor,
                        vertical_alignment=_settings_label_vertical_alignment(field),
                    )

                    if self._mode == SettingsPanelSaveMode.AUTOSAVE:
                        editor.value_changed.connect(
                            partial(self._autosave_field, field.key)
                        )
                    else:
                        editor.value_changed.connect(
                            partial(self._on_field_changed, field.key)
                        )

                tab_layout.addWidget(section)

            _harmonize_form_row_spacing(tab_form_layouts)
            tab_layout.addStretch(1)
            tab_content.setMinimumHeight(tab_content.sizeHint().height())
            tab_scroll.setWidget(tab_content)
            self._tabs.addTab(tab_scroll, tab_spec.title)

        if self._initial_tab_title and self._tabs is not None:
            for i in range(self._tabs.count()):
                if self._tabs.tabText(i) != self._initial_tab_title:
                    continue
                self._tabs.setCurrentIndex(i)
                break

        if self._mode == SettingsPanelSaveMode.AUTOSAVE:
            buttons = QDialogButtonBox(QDialogButtonBox.StandardButton.Close)
            buttons.rejected.connect(self.reject)
            buttons.accepted.connect(self.accept)
            root.addWidget(buttons)
            return

        self._button_box = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Save
            | QDialogButtonBox.StandardButton.Cancel
        )
        self._save_btn = self._button_box.button(QDialogButtonBox.StandardButton.Save)
        self._save_btn.setDefault(False)
        self._save_btn.setAutoDefault(False)
        self._save_btn.installEventFilter(self)
        self._button_box.accepted.connect(self._on_save)
        self._button_box.rejected.connect(self._on_cancel)
        root.addWidget(self._button_box)

    def _wire_editor_dependencies(self) -> None:
        labels_editor = self._editors.get(UserSettingKey.STATUS_LABELS)
        transitions_editor = self._editors.get(
            UserSettingKey.FLICKR_UPLOAD_LABEL_TRANSITIONS
        )
        upload_label_editor = self._editors.get(UserSettingKey.FLICKR_UPLOAD_LABEL)
        if labels_editor is not None:

            def provider():
                return list(labels_editor.get_value() or [])

            for editor in (transitions_editor, upload_label_editor):
                if editor is None:
                    continue
                set_provider = getattr(editor, "set_status_label_provider", None)
                if callable(set_provider):
                    set_provider(provider)

        self._sync_flickr_lifecycle_editors()

    def _should_include_field(self, field: FieldSpec) -> bool:
        if field.key not in _GCP_OCR_FIELD_KEYS:
            return True

        provider = get_runtime_setting(RuntimeSettingKey.OCR_TIME_SHIFT_PROVIDER)
        return provider != TimeShiftOcrProvider.APPLE_VISION

    def eventFilter(self, watched, event):  # noqa: N802
        if (
            isinstance(watched, QAbstractSpinBox)
            and event.type() == QEvent.Type.KeyPress
            and event.key() in (Qt.Key.Key_Return, Qt.Key.Key_Enter)
        ):
            watched.clearFocus()
            self.setFocus(Qt.FocusReason.OtherFocusReason)
            event.accept()
            return True

        if (
            isinstance(watched, QLineEdit)
            and event.type() == QEvent.Type.KeyPress
            and event.key() in (Qt.Key.Key_Return, Qt.Key.Key_Enter)
        ):
            watched.clearFocus()
            self.setFocus(Qt.FocusReason.OtherFocusReason)
            event.accept()
            return True

        if (
            hasattr(self, "_save_btn")
            and watched is self._save_btn
            and event.type() == QEvent.Type.KeyPress
            and event.key() in (Qt.Key.Key_Return, Qt.Key.Key_Enter)
        ):
            if self._save_btn.isEnabled():
                self._on_save()
            event.accept()
            return True
        return super().eventFilter(watched, event)

    def _install_line_edit_filters(self) -> None:
        for spin_box in self.findChildren(QAbstractSpinBox):
            spin_box.installEventFilter(self)
        for line_edit in self.findChildren(QLineEdit):
            line_edit.installEventFilter(self)

    def _load_initial_values(self):
        self._loading = True
        try:
            for key, editor in self._editors.items():
                value = get_user_setting(key)
                editor.set_value(value)
                editor.clear_error_hint()
                self._initial_values[key] = value
        finally:
            self._loading = False
        self._sync_flickr_lifecycle_editors()
        self._update_save_enabled()

    def _on_field_changed(self, key: UserSettingKey):
        if self._loading:
            return
        self._editors[key].clear_error_hint()
        if key == UserSettingKey.STATUS_LABELS:
            self._refresh_status_label_dependents()
        if key == UserSettingKey.FLICKR_UPLOAD_USE_LIFECYCLE:
            self._sync_flickr_lifecycle_editors()
        self._dirty = self._compute_dirty()
        self._update_save_enabled()

    def _all_editors_valid(self) -> bool:
        return all(editor.is_valid() for editor in self._editors.values())

    def _changed_editors_valid(self) -> bool:
        for key, editor in self._editors.items():
            value = editor.get_value()
            if not self._should_validate_editor(key, value):
                continue
            if not editor.is_valid():
                return False
        return True

    def _should_validate_editor(self, key: UserSettingKey, value: object) -> bool:
        if key == UserSettingKey.FLICKR_UPLOAD_LABEL_TRANSITIONS:
            return False
        if key == UserSettingKey.FLICKR_UPLOAD_LABEL:
            return self._flickr_lifecycle_enabled()
        if value != self._initial_values.get(key):
            return True
        return False

    def _flickr_lifecycle_enabled(self) -> bool:
        editor = self._editors.get(UserSettingKey.FLICKR_UPLOAD_USE_LIFECYCLE)
        return bool(editor is not None and editor.get_value())

    def _sync_flickr_lifecycle_editors(self) -> None:
        enabled = self._flickr_lifecycle_enabled()
        upload_label_editor = self._editors.get(UserSettingKey.FLICKR_UPLOAD_LABEL)
        transitions_editor = self._editors.get(
            UserSettingKey.FLICKR_UPLOAD_LABEL_TRANSITIONS
        )

        set_required = getattr(upload_label_editor, "set_required", None)
        if callable(set_required):
            set_required(enabled)
        elif upload_label_editor is not None:
            upload_label_editor.setEnabled(enabled)

        if transitions_editor is not None:
            transitions_editor.setEnabled(enabled)

    def _refresh_status_label_dependents(self) -> None:
        for key in (
            UserSettingKey.FLICKR_UPLOAD_LABEL,
            UserSettingKey.FLICKR_UPLOAD_LABEL_TRANSITIONS,
        ):
            editor = self._editors.get(key)
            if editor is None:
                continue
            refresh = getattr(editor, "refresh_status_labels", None)
            if callable(refresh):
                refresh()

    def _update_save_enabled(self) -> None:
        if hasattr(self, "_save_btn"):
            can_save = self._changed_editors_valid()
            self._save_btn.setEnabled(can_save)
            self._save_btn.setDefault(False)
            self._save_btn.setAutoDefault(False)

    def showEvent(self, event) -> None:  # noqa: N802
        super().showEvent(event)
        if self._initial_focus_cleared:
            return
        self._initial_focus_cleared = True
        QTimer.singleShot(0, self._clear_initial_focus)

    def _clear_initial_focus(self) -> None:
        current = self.focusWidget()
        if current is not None and current is not self:
            current.clearFocus()
        self.setFocus(Qt.FocusReason.ActiveWindowFocusReason)
        self._update_save_enabled()

    def _on_tab_changed(self, _index: int) -> None:
        QTimer.singleShot(0, self._clear_tab_focus)

    def _clear_tab_focus(self) -> None:
        current = self.focusWidget()
        if current is not None and current is not self:
            current.clearFocus()
        self.setFocus(Qt.FocusReason.OtherFocusReason)

    def _compute_dirty(self) -> bool:
        for key, editor in self._editors.items():
            if editor.get_value() != self._initial_values.get(key):
                return True
        return False

    def _validate_field(self, key: UserSettingKey, value: object) -> str | None:
        mandatory_spec = get_mandatory_setting_spec(key)
        if mandatory_spec is not None:
            if validate_mandatory_setting_value(mandatory_spec, value):
                return None

            if mandatory_spec.input_kind == MandatorySettingInputKind.DIRECTORY:
                return f"{mandatory_spec.label} must be an existing directory."
            if mandatory_spec.input_kind == MandatorySettingInputKind.EXECUTABLE_PATH:
                return f"{mandatory_spec.label} must be an existing executable file."
            return f"{mandatory_spec.label} is required."

        field = self._fields[key]
        if field.editor == EditorKind.PATH_DIR:
            if value and not os.path.isdir(str(value)):
                return f"The directory does not exist:\n{value}"
        if field.editor == EditorKind.PATH_FILE:
            if value and not os.path.isfile(str(value)):
                return f"The file does not exist:\n{value}"
        if field.editor == EditorKind.PATH_APP:
            if not value:
                return None
            path = str(value).strip()
            normalized_path = path
            if normalized_path != os.sep:
                normalized_path = normalized_path.rstrip(os.sep)
            if not normalized_path.lower().endswith(".app") or not os.path.isdir(path):
                return f"Application path must be an existing .app bundle.\n{value}"
        return None

    def _autosave_field(self, key: UserSettingKey):
        if self._loading:
            return

        editor = self._editors[key]
        editor.clear_error_hint()
        if not editor.is_valid():
            return

        value = editor.get_value()
        validation_error = self._validate_field(key, value)
        if validation_error is not None:
            field = self._fields[key]
            title = "Invalid Setting"
            if field.editor == EditorKind.PATH_DIR:
                title = "Invalid Directory"
            elif field.editor == EditorKind.PATH_FILE:
                title = "Invalid File"
            elif field.editor == EditorKind.PATH_APP:
                title = "Invalid Application"
            QMessageBox.warning(self, title, validation_error)
            editor.set_value(self._initial_values.get(key))
            return

        if value == self._initial_values.get(key):
            return

        set_user_setting(key, value)
        self._initial_values[key] = value
        self._changed_keys.add(key)
        self.setting_saved.emit(key)

    def _on_save(self):
        changed: dict[UserSettingKey, object] = {}
        errors: list[str] = []

        for editor in self._editors.values():
            editor.clear_error_hint()

        for key, editor in self._editors.items():
            value = editor.get_value()
            is_changed = value != self._initial_values.get(key)
            should_validate = self._should_validate_editor(key, value)
            if not is_changed and not should_validate:
                continue
            if should_validate and not editor.is_valid():
                return
            if should_validate:
                validation_error = self._validate_field(key, value)
                if validation_error is not None:
                    errors.append(validation_error)
                    self._show_mandatory_field_error_hint(key, validation_error)
                    continue
            if is_changed:
                changed[key] = value

        if errors:
            QMessageBox.warning(self, "Invalid Settings", "\n\n".join(errors))
            return

        for key, value in changed.items():
            set_user_setting(key, value)
            self._initial_values[key] = value
            self._changed_keys.add(key)
            self.setting_saved.emit(key)

        self._dirty = False
        self.accept()

    def _show_mandatory_field_error_hint(
        self,
        key: UserSettingKey,
        message: str,
    ) -> None:
        spec = get_mandatory_setting_spec(key)
        if spec is None:
            return

        auto_value = None
        if spec.default_resolver is not None:
            resolved = spec.default_resolver()
            if resolved is not None:
                resolved_text = str(resolved).strip()
                auto_value = resolved_text or None

        self._editors[key].show_error_hint(message, auto_value=auto_value)

    def _on_cancel(self):
        if not self._confirm_discard_changes_if_required(force=True):
            return
        self._reject_without_discard_confirmation()

    def _has_unsaved_changes(self) -> bool:
        return self._dirty
