"""Autogenerated settings dialog driven by schema descriptors."""

from __future__ import annotations

from functools import partial
import os
import sys

from PySide6.QtCore import QEvent, Qt, QTimer, Signal
from PySide6.QtWidgets import (
    QAbstractSpinBox,
    QDialog,
    QDialogButtonBox,
    QFormLayout,
    QGroupBox,
    QLineEdit,
    QMessageBox,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)

from piqopiqo.ssf.settings_state import (
    RuntimeSettingKey,
    SettingsPanelSaveMode,
    UserSettingKey,
    get_runtime_setting,
    get_user_setting,
    set_user_setting,
)

from .editors import BaseEditor, build_editor
from .schema import SETTINGS_TABS, EditorKind, FieldSpec


class SettingsDialog(QDialog):
    setting_saved = Signal(object)

    def __init__(self, parent=None, initial_tab_title: str | None = None):
        super().__init__(parent)
        self.setWindowTitle("Settings")
        self.resize(850, 620)

        self._editors: dict[UserSettingKey, BaseEditor] = {}
        self._fields: dict[UserSettingKey, FieldSpec] = {}
        self._initial_values: dict[UserSettingKey, object] = {}
        self._changed_keys: set[UserSettingKey] = set()
        self._loading = False
        self._dirty = False
        self._tabs: QTabWidget | None = None
        self._initial_tab_title = str(initial_tab_title or "").strip()
        self._initial_focus_cleared = False

        self._mode = get_runtime_setting(RuntimeSettingKey.SETTINGS_PANEL_SAVE_MODE)

        self._build_ui()
        self._install_line_edit_filters()
        self._load_initial_values()

    @property
    def changed_keys(self) -> set[UserSettingKey]:
        return set(self._changed_keys)

    def _build_ui(self):
        root = QVBoxLayout(self)

        self._tabs = QTabWidget(self)
        self._tabs.currentChanged.connect(self._on_tab_changed)
        root.addWidget(self._tabs)

        for tab_spec in SETTINGS_TABS:
            tab = QWidget(self)
            tab_layout = QVBoxLayout(tab)

            for group_spec in tab_spec.groups:
                group_box = QGroupBox(group_spec.title, tab)
                group_layout = QFormLayout(group_box)
                group_layout.setFieldGrowthPolicy(
                    QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow
                )
                group_layout.setFormAlignment(Qt.AlignmentFlag.AlignLeft)
                group_layout.setLabelAlignment(
                    Qt.AlignmentFlag.AlignLeft | Qt.AlignmentFlag.AlignVCenter
                )

                for field in group_spec.fields:
                    editor = build_editor(
                        field.editor,
                        choices=field.choices,
                        min_value=field.min_value,
                        max_value=field.max_value,
                    )
                    self._editors[field.key] = editor
                    self._fields[field.key] = field
                    group_layout.addRow(field.label, editor)

                    if self._mode == SettingsPanelSaveMode.AUTOSAVE:
                        editor.value_changed.connect(
                            partial(self._autosave_field, field.key)
                        )
                    else:
                        editor.value_changed.connect(self._on_field_changed)

                tab_layout.addWidget(group_box)

            tab_layout.addStretch(1)
            self._tabs.addTab(tab, tab_spec.title)

        if self._initial_tab_title and self._tabs is not None:
            for i in range(self._tabs.count()):
                if self._tabs.tabText(i) != self._initial_tab_title:
                    continue
                self._tabs.setCurrentIndex(i)
                break

        if self._mode == SettingsPanelSaveMode.AUTOSAVE:
            buttons = QDialogButtonBox(QDialogButtonBox.StandardButton.Close)
            buttons.rejected.connect(self.reject)
            buttons.accepted.connect(self.accept)
            root.addWidget(buttons)
            return

        self._button_box = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Save
            | QDialogButtonBox.StandardButton.Cancel
        )
        self._save_btn = self._button_box.button(QDialogButtonBox.StandardButton.Save)
        self._save_btn.setDefault(False)
        self._save_btn.setAutoDefault(False)
        self._save_btn.installEventFilter(self)
        self._button_box.accepted.connect(self._on_save)
        self._button_box.rejected.connect(self._on_cancel)
        root.addWidget(self._button_box)

    def eventFilter(self, watched, event):  # noqa: N802
        if (
            isinstance(watched, QAbstractSpinBox)
            and event.type() == QEvent.Type.KeyPress
            and event.key() in (Qt.Key.Key_Return, Qt.Key.Key_Enter)
        ):
            watched.clearFocus()
            self.setFocus(Qt.FocusReason.OtherFocusReason)
            event.accept()
            return True

        if (
            isinstance(watched, QLineEdit)
            and event.type() == QEvent.Type.KeyPress
            and event.key() in (Qt.Key.Key_Return, Qt.Key.Key_Enter)
        ):
            watched.clearFocus()
            self.setFocus(Qt.FocusReason.OtherFocusReason)
            event.accept()
            return True

        if (
            hasattr(self, "_save_btn")
            and watched is self._save_btn
            and event.type() == QEvent.Type.KeyPress
            and event.key() in (Qt.Key.Key_Return, Qt.Key.Key_Enter)
        ):
            if self._save_btn.isEnabled():
                self._on_save()
            event.accept()
            return True
        return super().eventFilter(watched, event)

    def _install_line_edit_filters(self) -> None:
        for spin_box in self.findChildren(QAbstractSpinBox):
            spin_box.installEventFilter(self)
        for line_edit in self.findChildren(QLineEdit):
            line_edit.installEventFilter(self)

    def _load_initial_values(self):
        self._loading = True
        try:
            for key, editor in self._editors.items():
                value = get_user_setting(key)
                editor.set_value(value)
                self._initial_values[key] = value
        finally:
            self._loading = False
        self._update_save_enabled()

    def _on_field_changed(self):
        if self._loading:
            return
        self._dirty = self._compute_dirty()
        self._update_save_enabled()

    def _all_editors_valid(self) -> bool:
        return all(editor.is_valid() for editor in self._editors.values())

    def _changed_editors_valid(self) -> bool:
        for key, editor in self._editors.items():
            if editor.get_value() == self._initial_values.get(key):
                continue
            if not editor.is_valid():
                return False
        return True

    def _update_save_enabled(self) -> None:
        if hasattr(self, "_save_btn"):
            can_save = self._changed_editors_valid()
            self._save_btn.setEnabled(can_save)
            self._save_btn.setDefault(False)
            self._save_btn.setAutoDefault(False)

    def showEvent(self, event) -> None:  # noqa: N802
        super().showEvent(event)
        if self._initial_focus_cleared:
            return
        self._initial_focus_cleared = True
        QTimer.singleShot(0, self._clear_initial_focus)

    def _clear_initial_focus(self) -> None:
        current = self.focusWidget()
        if current is not None and current is not self:
            current.clearFocus()
        self.setFocus(Qt.FocusReason.ActiveWindowFocusReason)
        self._update_save_enabled()

    def _on_tab_changed(self, _index: int) -> None:
        QTimer.singleShot(0, self._clear_tab_focus)

    def _clear_tab_focus(self) -> None:
        current = self.focusWidget()
        if current is not None and current is not self:
            current.clearFocus()
        self.setFocus(Qt.FocusReason.OtherFocusReason)

    def _compute_dirty(self) -> bool:
        for key, editor in self._editors.items():
            if editor.get_value() != self._initial_values.get(key):
                return True
        return False

    def _validate_field(self, key: UserSettingKey, value: object) -> bool:
        field = self._fields[key]
        if field.editor == EditorKind.PATH_DIR:
            if value and not os.path.isdir(str(value)):
                QMessageBox.warning(
                    self,
                    "Invalid Directory",
                    f"The directory does not exist:\n{value}",
                )
                return False
        if field.editor == EditorKind.PATH_FILE:
            if value and not os.path.isfile(str(value)):
                QMessageBox.warning(
                    self,
                    "Invalid File",
                    f"The file does not exist:\n{value}",
                )
                return False
        if field.editor == EditorKind.PATH_APP:
            if not value:
                return True
            path = str(value).strip()
            normalized_path = path
            if normalized_path != os.sep:
                normalized_path = normalized_path.rstrip(os.sep)
            if sys.platform == "darwin":
                if not normalized_path.lower().endswith(".app") or not os.path.isdir(
                    path
                ):
                    QMessageBox.warning(
                        self,
                        "Invalid Application",
                        f"Application path must be an existing .app bundle.\n{value}",
                    )
                    return False
            elif not os.path.exists(path):
                QMessageBox.warning(
                    self,
                    "Invalid Application",
                    f"The path does not exist:\n{value}",
                )
                return False
        return True

    def _autosave_field(self, key: UserSettingKey):
        if self._loading:
            return

        editor = self._editors[key]
        if not editor.is_valid():
            return

        value = editor.get_value()
        if not self._validate_field(key, value):
            editor.set_value(self._initial_values.get(key))
            return

        if value == self._initial_values.get(key):
            return

        set_user_setting(key, value)
        self._initial_values[key] = value
        self._changed_keys.add(key)
        self.setting_saved.emit(key)

    def _on_save(self):
        changed: dict[UserSettingKey, object] = {}

        for key, editor in self._editors.items():
            value = editor.get_value()
            if value == self._initial_values.get(key):
                continue
            if not editor.is_valid():
                return
            if not self._validate_field(key, value):
                return
            changed[key] = value

        for key, value in changed.items():
            set_user_setting(key, value)
            self._initial_values[key] = value
            self._changed_keys.add(key)
            self.setting_saved.emit(key)

        self._dirty = False
        self.accept()

    def _on_cancel(self):
        if self._dirty:
            answer = QMessageBox.question(
                self,
                "Discard changes",
                "Some settings have changed. Discard them?",
                QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
                QMessageBox.StandardButton.No,
            )
            if answer != QMessageBox.StandardButton.Yes:
                return

        self.reject()
