"""Editor widgets used by the autogenerated settings dialog."""

from __future__ import annotations

from PySide6.QtCore import Signal
from PySide6.QtWidgets import (
    QComboBox,
    QFileDialog,
    QHBoxLayout,
    QLineEdit,
    QPlainTextEdit,
    QPushButton,
    QSpinBox,
    QWidget,
)

from .schema import ChoiceOption, EditorKind
from .shortcuts_editor import ShortcutsEditor
from .status_labels_editor import StatusLabelsEditor


class BaseEditor(QWidget):
    value_changed = Signal()

    def set_value(self, value):
        raise NotImplementedError

    def get_value(self):
        raise NotImplementedError


class TextEditor(BaseEditor):
    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._line_edit = QLineEdit()
        self._line_edit.editingFinished.connect(self.value_changed)
        layout.addWidget(self._line_edit)

    def set_value(self, value):
        self._line_edit.setText("" if value is None else str(value))

    def get_value(self):
        return self._line_edit.text().strip()


class NumberEditor(BaseEditor):
    def __init__(self, min_value: int | None = None, max_value: int | None = None):
        super().__init__()
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._spin = QSpinBox()
        self._spin.setRange(min_value or -999999, max_value or 999999)
        self._spin.valueChanged.connect(self.value_changed)
        layout.addWidget(self._spin)

    def set_value(self, value):
        self._spin.setValue(int(value))

    def get_value(self):
        return int(self._spin.value())


class ChoiceEditor(BaseEditor):
    def __init__(self, choices: tuple[ChoiceOption, ...]):
        super().__init__()
        self._choices = choices

        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._combo = QComboBox()
        for option in choices:
            self._combo.addItem(option.label, option.value)
        self._combo.currentIndexChanged.connect(self.value_changed)
        layout.addWidget(self._combo)

    def set_value(self, value):
        for idx, option in enumerate(self._choices):
            if option.value == value:
                self._combo.setCurrentIndex(idx)
                return
            # Value can be serialized string while choice is enum.
            if str(option.value) == str(value):
                self._combo.setCurrentIndex(idx)
                return

    def get_value(self):
        return self._combo.currentData()


class PathEditor(BaseEditor):
    def __init__(self, *, is_file: bool):
        super().__init__()
        self._is_file = is_file

        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._line_edit = QLineEdit()
        self._line_edit.editingFinished.connect(self.value_changed)
        layout.addWidget(self._line_edit)

        browse_btn = QPushButton("Browse")
        browse_btn.clicked.connect(self._browse)
        layout.addWidget(browse_btn)

    def _browse(self):
        current = self._line_edit.text().strip()
        if self._is_file:
            value, _ = QFileDialog.getOpenFileName(self, "Select File", current or "")
        else:
            value = QFileDialog.getExistingDirectory(
                self,
                "Select Folder",
                current or "",
                QFileDialog.Option.ShowDirsOnly | QFileDialog.Option.ReadOnly,
            )

        if value:
            self._line_edit.setText(value)
            self.value_changed.emit()

    def set_value(self, value):
        self._line_edit.setText("" if value is None else str(value))

    def get_value(self):
        return self._line_edit.text().strip()


class _FocusOutPlainTextEdit(QPlainTextEdit):
    focus_left = Signal()

    def focusOutEvent(self, event):
        self.focus_left.emit()
        super().focusOutEvent(event)


class ListTextEditor(BaseEditor):
    def __init__(self):
        super().__init__()
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._text_edit = _FocusOutPlainTextEdit()
        self._text_edit.setPlaceholderText("One value per line")
        self._text_edit.focus_left.connect(self.value_changed)
        layout.addWidget(self._text_edit)

    def set_value(self, value):
        lines = [str(v) for v in (value or [])]
        self._text_edit.setPlainText("\n".join(lines))

    def get_value(self):
        raw = self._text_edit.toPlainText().splitlines()
        return [line.strip() for line in raw if line.strip()]


class StatusLabelsEditorAdapter(BaseEditor):
    def __init__(self):
        super().__init__()
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._editor = StatusLabelsEditor()
        self._editor.value_changed.connect(self.value_changed)
        layout.addWidget(self._editor)

    def set_value(self, value):
        self._editor.set_value(value)

    def get_value(self):
        return self._editor.get_value()


class ShortcutsEditorAdapter(BaseEditor):
    def __init__(self):
        super().__init__()
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._editor = ShortcutsEditor()
        self._editor.value_changed.connect(self.value_changed)
        layout.addWidget(self._editor)

    def set_value(self, value):
        self._editor.set_value(value)

    def get_value(self):
        return self._editor.get_value()


def build_editor(kind: EditorKind, **kwargs) -> BaseEditor:
    if kind == EditorKind.TEXT:
        return TextEditor()
    if kind == EditorKind.NUMBER:
        return NumberEditor(
            min_value=kwargs.get("min_value"),
            max_value=kwargs.get("max_value"),
        )
    if kind == EditorKind.CHOICE:
        return ChoiceEditor(kwargs.get("choices") or ())
    if kind == EditorKind.PATH_DIR:
        return PathEditor(is_file=False)
    if kind == EditorKind.PATH_FILE:
        return PathEditor(is_file=True)
    if kind == EditorKind.LIST_TEXT:
        return ListTextEditor()
    if kind == EditorKind.STATUS_LABELS:
        return StatusLabelsEditorAdapter()
    if kind == EditorKind.SHORTCUTS:
        return ShortcutsEditorAdapter()

    raise ValueError(f"Unsupported editor kind: {kind}")
