"""Editor widgets used by the autogenerated settings dialog."""

from __future__ import annotations

from collections.abc import Callable
import os
import sys

from PySide6.QtCore import Signal
from PySide6.QtWidgets import (
    QComboBox,
    QFileDialog,
    QHBoxLayout,
    QLineEdit,
    QPlainTextEdit,
    QPushButton,
    QSizePolicy,
    QSpinBox,
    QWidget,
)

from .schema import ChoiceOption, EditorKind
from .shortcuts_editor import ShortcutsEditor
from .status_labels_editor import StatusLabelsEditor


class BaseEditor(QWidget):
    value_changed = Signal()

    def set_value(self, value):
        raise NotImplementedError

    def get_value(self):
        raise NotImplementedError


class TextEditor(BaseEditor):
    def __init__(self, parent=None):
        super().__init__(parent)
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._line_edit = QLineEdit()
        self._line_edit.editingFinished.connect(self.value_changed)
        layout.addWidget(self._line_edit)

    def set_value(self, value):
        self._line_edit.setText("" if value is None else str(value))

    def get_value(self):
        return self._line_edit.text().strip()


class NumberEditor(BaseEditor):
    def __init__(self, min_value: int | None = None, max_value: int | None = None):
        super().__init__()
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._spin = QSpinBox()
        self._spin.setRange(min_value or -999999, max_value or 999999)
        self._spin.valueChanged.connect(self.value_changed)
        layout.addWidget(self._spin)

    def set_value(self, value):
        self._spin.setValue(int(value))

    def get_value(self):
        return int(self._spin.value())


class ChoiceEditor(BaseEditor):
    def __init__(self, choices: tuple[ChoiceOption, ...]):
        super().__init__()
        self._choices = choices

        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._combo = QComboBox()
        for option in choices:
            self._combo.addItem(option.label, option.value)
        self._combo.currentIndexChanged.connect(self.value_changed)
        layout.addWidget(self._combo)

    def set_value(self, value):
        for idx, option in enumerate(self._choices):
            if option.value == value:
                self._combo.setCurrentIndex(idx)
                return
            # Value can be serialized string while choice is enum.
            if str(option.value) == str(value):
                self._combo.setCurrentIndex(idx)
                return

    def get_value(self):
        return self._combo.currentData()


class PathEditor(BaseEditor):
    def __init__(
        self,
        *,
        is_file: bool,
        browse_title: str,
        start_dir_resolver: Callable[[str], str] | None = None,
    ):
        super().__init__()
        self._is_file = is_file
        self._browse_title = browse_title
        self._start_dir_resolver = start_dir_resolver

        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(8)
        self.setSizePolicy(
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Fixed,
        )

        self._line_edit = QLineEdit()
        self._line_edit.editingFinished.connect(self.value_changed)
        self._line_edit.setSizePolicy(
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Fixed,
        )
        layout.addWidget(self._line_edit)
        layout.setStretch(0, 1)

        browse_btn = QPushButton("Browse")
        browse_btn.clicked.connect(self._browse)
        browse_btn.setSizePolicy(
            QSizePolicy.Policy.Fixed,
            QSizePolicy.Policy.Fixed,
        )
        layout.addWidget(browse_btn)

    def _browse(self):
        current = self._line_edit.text().strip()
        start_dir = self._get_start_dir(current)
        if self._is_file:
            value, _ = QFileDialog.getOpenFileName(
                self,
                self._browse_title,
                start_dir,
            )
        else:
            value = QFileDialog.getExistingDirectory(
                self,
                self._browse_title,
                start_dir,
                QFileDialog.Option.ShowDirsOnly | QFileDialog.Option.ReadOnly,
            )

        if value:
            self._line_edit.setText(value)
            self.value_changed.emit()

    def set_value(self, value):
        self._line_edit.setText("" if value is None else str(value))

    def get_value(self):
        return self._line_edit.text().strip()

    def _get_start_dir(self, current: str) -> str:
        if self._start_dir_resolver is not None:
            return self._start_dir_resolver(current)
        return current or ""


def _resolve_app_path_start_dir(current: str) -> str:
    if current:
        path = os.path.expanduser(current)
        if path != os.sep:
            path = path.rstrip(os.sep)
        if path.lower().endswith(".app"):
            return os.path.dirname(path) or path
        if os.path.isdir(path):
            return path
        parent = os.path.dirname(path)
        if parent:
            return parent

    if sys.platform == "darwin":
        return "/Applications"
    return os.path.expanduser("~")


class AppPathEditor(PathEditor):
    def __init__(self):
        super().__init__(
            is_file=False,
            browse_title="Select Application",
            start_dir_resolver=_resolve_app_path_start_dir,
        )


class _FocusOutPlainTextEdit(QPlainTextEdit):
    focus_left = Signal()

    def focusOutEvent(self, event):
        self.focus_left.emit()
        super().focusOutEvent(event)


class ListTextEditor(BaseEditor):
    def __init__(self):
        super().__init__()
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._text_edit = _FocusOutPlainTextEdit()
        self._text_edit.setPlaceholderText("One value per line")
        self._text_edit.focus_left.connect(self.value_changed)
        layout.addWidget(self._text_edit)

    def set_value(self, value):
        lines = [str(v) for v in (value or [])]
        self._text_edit.setPlainText("\n".join(lines))

    def get_value(self):
        raw = self._text_edit.toPlainText().splitlines()
        return [line.strip() for line in raw if line.strip()]


class StatusLabelsEditorAdapter(BaseEditor):
    def __init__(self):
        super().__init__()
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._editor = StatusLabelsEditor()
        self._editor.value_changed.connect(self.value_changed)
        layout.addWidget(self._editor)

    def set_value(self, value):
        self._editor.set_value(value)

    def get_value(self):
        return self._editor.get_value()


class ShortcutsEditorAdapter(BaseEditor):
    def __init__(self):
        super().__init__()
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._editor = ShortcutsEditor()
        self._editor.value_changed.connect(self.value_changed)
        layout.addWidget(self._editor)

    def set_value(self, value):
        self._editor.set_value(value)

    def get_value(self):
        return self._editor.get_value()


def build_editor(kind: EditorKind, **kwargs) -> BaseEditor:
    if kind == EditorKind.TEXT:
        return TextEditor()
    if kind == EditorKind.NUMBER:
        return NumberEditor(
            min_value=kwargs.get("min_value"),
            max_value=kwargs.get("max_value"),
        )
    if kind == EditorKind.CHOICE:
        return ChoiceEditor(kwargs.get("choices") or ())
    if kind == EditorKind.PATH_DIR:
        return PathEditor(is_file=False, browse_title="Select Folder")
    if kind == EditorKind.PATH_FILE:
        return PathEditor(is_file=True, browse_title="Select File")
    if kind == EditorKind.PATH_APP:
        return AppPathEditor()
    if kind == EditorKind.LIST_TEXT:
        return ListTextEditor()
    if kind == EditorKind.STATUS_LABELS:
        return StatusLabelsEditorAdapter()
    if kind == EditorKind.SHORTCUTS:
        return ShortcutsEditorAdapter()

    raise ValueError(f"Unsupported editor kind: {kind}")
