"""Descriptor schema for the autogenerated settings panel."""

from __future__ import annotations

from enum import Enum, auto

from attrs import define

from piqopiqo.color_management import ScreenColorProfileMode
from piqopiqo.model import OnFullscreenExitMultipleSelected
from piqopiqo.ssf.settings_state import UserSettingKey


class EditorKind(Enum):
    PATH_DIR = auto()
    PATH_FILE = auto()
    PATH_APP = auto()
    TEXT = auto()
    NUMBER = auto()
    CHOICE = auto()
    BOOL = auto()
    LIST_TEXT = auto()
    STATUS_LABELS = auto()
    SHORTCUTS = auto()
    MANUAL_LENSES = auto()


@define(frozen=True)
class ChoiceOption:
    label: str
    value: object


@define(frozen=True)
class FieldSpec:
    key: UserSettingKey
    label: str
    editor: EditorKind
    choices: list[ChoiceOption] = ()
    min_value: int | None = None
    max_value: int | None = None


@define(frozen=True)
class GroupSpec:
    title: str
    fields: list[FieldSpec]


@define(frozen=True)
class TabSpec:
    title: str
    groups: list[GroupSpec]


SETTINGS_TABS: list[TabSpec] = [
    TabSpec(
        title="Core",
        groups=[
            GroupSpec(
                title="Thumbnails + Metadata DB",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.CACHE_BASE_DIR,
                        label="Cache Base Directory",
                        editor=EditorKind.PATH_DIR,
                    ),
                ],
            ),
            GroupSpec(
                title="Exiftool",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.EXIFTOOL_PATH,
                        label="Path",
                        editor=EditorKind.PATH_FILE,
                    ),
                ],
            ),
        ],
    ),
    TabSpec(
        title="Interface",
        groups=[
            GroupSpec(
                title="Grid",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.NUM_COLUMNS,
                        label="Number of Columns",
                        editor=EditorKind.NUMBER,
                        min_value=1,
                        max_value=50,
                    ),
                ],
            ),
            GroupSpec(
                title="Fullscreen",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.ON_FULLSCREEN_EXIT_SELECTION_MODE,
                        label="Fullscreen Exit Behavior",
                        editor=EditorKind.CHOICE,
                        choices=[
                            ChoiceOption(
                                label="Keep Selection",
                                value=OnFullscreenExitMultipleSelected.KEEP_SELECTION,
                            ),
                            ChoiceOption(
                                label="Select Last Viewed",
                                value=(
                                    OnFullscreenExitMultipleSelected.SELECT_LAST_VIEWED
                                ),
                            ),
                        ],
                    ),
                ],
            ),
            GroupSpec(
                title="Color",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.FORCE_SRGB,
                        label="Force sRGB",
                        editor=EditorKind.BOOL,
                    ),
                    FieldSpec(
                        key=UserSettingKey.SCREEN_COLOR_PROFILE,
                        label="Screen Color Profile",
                        editor=EditorKind.CHOICE,
                        choices=[
                            ChoiceOption(
                                label="From main screen",
                                value=ScreenColorProfileMode.FROM_MAIN_SCREEN,
                            ),
                            ChoiceOption(
                                label="sRGB",
                                value=ScreenColorProfileMode.SRGB,
                            ),
                            ChoiceOption(
                                label="Display P3",
                                value=ScreenColorProfileMode.DISPLAY_P3,
                            ),
                            ChoiceOption(
                                label="Bt2020",
                                value=ScreenColorProfileMode.BT2020,
                            ),
                            ChoiceOption(
                                label="No conversion",
                                value=ScreenColorProfileMode.NO_CONVERSION,
                            ),
                        ],
                    ),
                ],
            ),
            GroupSpec(
                title="Metadata Panel",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.SHOW_DESCRIPTION_FIELD,
                        label="Show description field",
                        editor=EditorKind.BOOL,
                    ),
                    FieldSpec(
                        key=UserSettingKey.PROTECT_NON_TEXT_METADATA,
                        label="Protect non-text metadata fields",
                        editor=EditorKind.BOOL,
                    ),
                ],
            ),
            GroupSpec(
                title="EXIF Panel",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.CUSTOM_EXIF_FIELDS,
                        label="Custom EXIF Fields",
                        editor=EditorKind.LIST_TEXT,
                    ),
                ],
            ),
        ],
    ),
    TabSpec(
        title="Labels + Shortcuts",
        groups=[
            GroupSpec(
                title="Status Labels",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.STATUS_LABELS,
                        label="",
                        editor=EditorKind.STATUS_LABELS,
                    ),
                    FieldSpec(
                        key=UserSettingKey.FILTER_IN_FULLSCREEN,
                        label="Filter in fullscreen",
                        editor=EditorKind.BOOL,
                    ),
                ],
            ),
            GroupSpec(
                title="Shortcuts",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.SHORTCUTS,
                        label="",
                        editor=EditorKind.SHORTCUTS,
                    ),
                ],
            ),
        ],
    ),
    TabSpec(
        title="External/Tools",
        groups=[
            GroupSpec(
                title="External Apps",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.EXTERNAL_VIEWER,
                        label="External Viewer",
                        editor=EditorKind.PATH_APP,
                    ),
                    FieldSpec(
                        key=UserSettingKey.EXTERNAL_EDITOR,
                        label="External Editor",
                        editor=EditorKind.PATH_APP,
                    ),
                ],
            ),
            GroupSpec(
                title="Copy SD",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.COPY_SD_BASE_EXTERNAL_FOLDER,
                        label="Copy SD Base External Folder",
                        editor=EditorKind.PATH_DIR,
                    ),
                    FieldSpec(
                        key=UserSettingKey.SDCARD_NAMES,
                        label="SD Card Names",
                        editor=EditorKind.LIST_TEXT,
                    ),
                ],
            ),
            GroupSpec(
                title="GPX",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.TIME_SHIFT_UNKNOWN_FOLDER_IGNORE,
                        label="Ingore last timeshift if unknown folder",
                        editor=EditorKind.BOOL,
                    ),
                    FieldSpec(
                        key=UserSettingKey.GPX_IGNORE_OFFSET,
                        label="Ignore Offset",
                        editor=EditorKind.BOOL,
                    ),
                    FieldSpec(
                        key=UserSettingKey.GPX_TIMEZONE,
                        label="Timezone",
                        editor=EditorKind.TEXT,
                    ),
                    FieldSpec(
                        key=UserSettingKey.GPX_KML_FOLDER,
                        label="KML Folder",
                        editor=EditorKind.PATH_DIR,
                    ),
                    FieldSpec(
                        key=UserSettingKey.GCP_SA_KEY_PATH,
                        label="Service Account JSON Key",
                        editor=EditorKind.PATH_FILE,
                    ),
                    FieldSpec(
                        key=UserSettingKey.GCP_PROJECT,
                        label="GCP Project Override",
                        editor=EditorKind.TEXT,
                    ),
                ],
            ),
            GroupSpec(
                title="Flickr",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.FLICKR_API_KEY,
                        label="Flickr API key",
                        editor=EditorKind.TEXT,
                    ),
                    FieldSpec(
                        key=UserSettingKey.FLICKR_API_SECRET,
                        label="Flickr API secret",
                        editor=EditorKind.TEXT,
                    ),
                ],
            ),
            GroupSpec(
                title="Manual Lens",
                fields=[
                    FieldSpec(
                        key=UserSettingKey.MANUAL_LENSES,
                        label="Lens presets",
                        editor=EditorKind.MANUAL_LENSES,
                    ),
                ],
            ),
        ],
    ),
]


def iter_all_field_specs() -> list[FieldSpec]:
    fields: list[FieldSpec] = []
    for tab in SETTINGS_TABS:
        for group in tab.groups:
            fields.extend(group.fields)
    return fields
