"""Descriptor schema for the autogenerated settings panel."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from ..model import OnFullscreenExitMultipleSelected
from ..settings_state import UserSettingKey


class EditorKind(StrEnum):
    PATH_DIR = "pathDir"
    PATH_FILE = "pathFile"
    TEXT = "text"
    NUMBER = "number"
    CHOICE = "choice"
    LIST_TEXT = "listText"
    STATUS_LABELS = "statusLabels"
    SHORTCUTS = "shortcuts"


@dataclass(frozen=True)
class ChoiceOption:
    label: str
    value: object


@dataclass(frozen=True)
class FieldSpec:
    key: UserSettingKey
    label: str
    editor: EditorKind
    choices: tuple[ChoiceOption, ...] = ()
    min_value: int | None = None
    max_value: int | None = None


@dataclass(frozen=True)
class GroupSpec:
    title: str
    fields: tuple[FieldSpec, ...]


@dataclass(frozen=True)
class TabSpec:
    title: str
    groups: tuple[GroupSpec, ...]


SETTINGS_TABS: tuple[TabSpec, ...] = (
    TabSpec(
        title="Paths",
        groups=(
            GroupSpec(
                title="Storage",
                fields=(
                    FieldSpec(
                        key=UserSettingKey.CACHE_BASE_DIR,
                        label="Cache Base Directory",
                        editor=EditorKind.PATH_DIR,
                    ),
                    FieldSpec(
                        key=UserSettingKey.COPY_SD_BASE_EXTERNAL_FOLDER,
                        label="Copy SD Base External Folder",
                        editor=EditorKind.PATH_DIR,
                    ),
                ),
            ),
            GroupSpec(
                title="Tools",
                fields=(
                    FieldSpec(
                        key=UserSettingKey.EXIFTOOL_PATH,
                        label="Exiftool Path",
                        editor=EditorKind.PATH_FILE,
                    ),
                ),
            ),
        ),
    ),
    TabSpec(
        title="Grid/Display",
        groups=(
            GroupSpec(
                title="Grid",
                fields=(
                    FieldSpec(
                        key=UserSettingKey.NUM_COLUMNS,
                        label="Number of Columns",
                        editor=EditorKind.NUMBER,
                        min_value=1,
                        max_value=50,
                    ),
                    FieldSpec(
                        key=UserSettingKey.ON_FULLSCREEN_EXIT,
                        label="Fullscreen Exit Behavior",
                        editor=EditorKind.CHOICE,
                        choices=(
                            ChoiceOption(
                                label="Keep Selection",
                                value=OnFullscreenExitMultipleSelected.KEEP_SELECTION,
                            ),
                            ChoiceOption(
                                label="Select Last Viewed",
                                value=(
                                    OnFullscreenExitMultipleSelected.SELECT_LAST_VIEWED
                                ),
                            ),
                        ),
                    ),
                    FieldSpec(
                        key=UserSettingKey.CUSTOM_EXIF_FIELDS,
                        label="Custom EXIF Fields",
                        editor=EditorKind.LIST_TEXT,
                    ),
                ),
            ),
        ),
    ),
    TabSpec(
        title="Labels + Shortcuts",
        groups=(
            GroupSpec(
                title="Status Labels",
                fields=(
                    FieldSpec(
                        key=UserSettingKey.STATUS_LABELS,
                        label="Status Labels",
                        editor=EditorKind.STATUS_LABELS,
                    ),
                ),
            ),
            GroupSpec(
                title="Keyboard",
                fields=(
                    FieldSpec(
                        key=UserSettingKey.SHORTCUTS,
                        label="Shortcuts",
                        editor=EditorKind.SHORTCUTS,
                    ),
                ),
            ),
        ),
    ),
    TabSpec(
        title="External/Workflow",
        groups=(
            GroupSpec(
                title="External Apps",
                fields=(
                    FieldSpec(
                        key=UserSettingKey.EXTERNAL_VIEWER,
                        label="External Viewer",
                        editor=EditorKind.TEXT,
                    ),
                    FieldSpec(
                        key=UserSettingKey.EXTERNAL_EDITOR,
                        label="External Editor",
                        editor=EditorKind.TEXT,
                    ),
                ),
            ),
        ),
    ),
)


def iter_all_field_specs() -> list[FieldSpec]:
    fields: list[FieldSpec] = []
    for tab in SETTINGS_TABS:
        for group in tab.groups:
            fields.extend(group.fields)
    return fields
