"""Application state persistence using QSettings."""

from enum import StrEnum
import json
import logging
import os
from pathlib import Path
import sys

from attrs import define
from PySide6.QtCore import QByteArray, QSettings

logger = logging.getLogger(__name__)


# Application identity constants (used by QCoreApplication and support paths)
APP_NAME = "PiqoPiqo"
ORG_NAME = "Guilhem V"
ORG_DOMAIN = "com.vellut"


class StateGroup(StrEnum):
    APP_STATE = "AppState"
    QT = "AppState/Qt"


class StateKey(StrEnum):
    # AppState group
    LAST_FOLDER = "lastFolder"
    COPY_SD_EJECT = "copySDEject"
    COPY_SD_NAME_SUFFIX = "copySdNameSuffix"
    COPY_SD_DATE_SPEC = "copySdDateSpec"
    # AppState/Qt group
    WINDOW_GEOMETRY = "windowGeometry"
    WINDOW_STATE = "windowState"
    MAIN_SPLITTER = "mainSplitter"
    RIGHT_SPLITTER = "rightSplitter"


@define
class StateDef:
    """Definition of a single state entry: group, stored type, default."""

    group: StateGroup
    typ: type = str  # Python type used for QSettings read/write
    default: object = None  # None means "no default, returns None when unset"


# Single source of truth for every state key.
_REGISTRY: dict[StateKey, StateDef] = {
    StateKey.LAST_FOLDER: StateDef(StateGroup.APP_STATE),
    StateKey.COPY_SD_EJECT: StateDef(StateGroup.APP_STATE, bool, True),
    StateKey.COPY_SD_NAME_SUFFIX: StateDef(StateGroup.APP_STATE, str, ""),
    StateKey.COPY_SD_DATE_SPEC: StateDef(StateGroup.APP_STATE, str, "since:last"),
    StateKey.WINDOW_GEOMETRY: StateDef(StateGroup.QT, QByteArray),
    StateKey.WINDOW_STATE: StateDef(StateGroup.QT, QByteArray),
    StateKey.MAIN_SPLITTER: StateDef(StateGroup.QT, QByteArray),
    StateKey.RIGHT_SPLITTER: StateDef(StateGroup.QT, QByteArray),
}


class StateStore:
    """Abstraction over QSettings for typed state persistence.

    Supports a ``dyn`` mode where all reads/writes are in-memory only
    (nothing is persisted to disk).
    """

    def __init__(self, dyn: bool = False):
        self._dyn = dyn
        self._memory: dict[str, object] = {}

        if not dyn:
            self._settings = QSettings()
        else:
            self._settings = None

    def get(self, key: StateKey):
        """Read a state value. Returns the typed value, the default, or None."""
        entry = _REGISTRY[key]
        full_key = f"{entry.group}/{key}"

        # In-memory cache (values set this session)
        if full_key in self._memory:
            return self._memory[full_key]

        # In dyn mode, return default directly
        if self._dyn:
            return entry.default

        # Key not in QSettings at all -> return default (which may be None)
        if not self._settings.contains(full_key):
            return entry.default

        # Read from QSettings with explicit type
        if entry.typ is QByteArray:
            return self._settings.value(full_key, type=QByteArray)
        elif entry.typ is bool:
            return self._settings.value(full_key, type=bool)
        elif entry.typ is int:
            return self._settings.value(full_key, type=int)
        elif entry.typ is float:
            return self._settings.value(full_key, type=float)
        elif entry.typ in (dict, list, tuple):
            raw = self._settings.value(full_key, type=str)
            try:
                return json.loads(raw)
            except (json.JSONDecodeError, TypeError):
                return entry.default
        else:
            return self._settings.value(full_key, type=str)

    def set(self, key: StateKey, value):
        """Write a state value. In dyn mode, only updates in-memory cache."""
        entry = _REGISTRY[key]
        full_key = f"{entry.group}/{key}"

        self._memory[full_key] = value

        if self._dyn:
            return

        # Serialize for QSettings
        if value is None:
            self._settings.setValue(full_key, "")
        elif entry.typ in (dict, list, tuple):
            self._settings.setValue(full_key, json.dumps(value))
        else:
            self._settings.setValue(full_key, value)


# Module-level singleton
_store: StateStore | None = None


def init_state(dyn: bool = False) -> StateStore:
    """Initialize the global StateStore. Call once after QCoreApplication setup."""
    global _store
    _store = StateStore(dyn=dyn)
    return _store


def get_state() -> StateStore:
    """Return the global StateStore instance."""
    if _store is None:
        raise RuntimeError("State not initialized. Call init_state() first.")
    return _store


# dir for default cache / additional files generated by the application
def get_support_dir() -> Path:
    """Get the platform-specific application support directory.

    Returns:
        Path to the support directory:
        - macOS: ~/Library/Application Support/PiqoPiqo/
        - Windows: %APPDATA%/PiqoPiqo/
        - Linux: ~/.config/piqopiqo/
    """
    if sys.platform == "darwin":
        # macOS
        base = Path.home() / "Library" / "Application Support"
        support_dir = base / APP_NAME
    elif sys.platform == "win32":
        # Windows
        appdata = os.environ.get("APPDATA")
        if appdata:
            base = Path(appdata)
        else:
            base = Path.home() / "AppData" / "Roaming"
        support_dir = base / APP_NAME
    else:
        # Linux and others
        xdg_config = os.environ.get("XDG_CONFIG_HOME")
        if xdg_config:
            base = Path(xdg_config)
        else:
            base = Path.home() / ".config"
        support_dir = base / APP_NAME.lower()

    # Create directory if it doesn't exist
    support_dir.mkdir(parents=True, exist_ok=True)
    return support_dir


def get_cache_base_dir() -> Path:
    """Get the base directory for all cache data.

    Returns:
        Path to the cache base directory inside the support directory.
    """
    cache_dir = get_support_dir() / "cache"
    cache_dir.mkdir(parents=True, exist_ok=True)
    return cache_dir
