// Auto-generated by cbindgen. Do not edit manually.


#ifndef CORE_LIB_H
#define CORE_LIB_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Returns a pointer to a null-terminated static C string "Hello from Rust!".
 * The string has static lifetime so no free function is required yet.
 *
 * # Safety
 * The returned pointer is valid for the lifetime of the program and must not
 * be freed. It points to immutable memory containing a NUL-terminated string.
 */
const char *hello_from_rust(void);

#endif  /* CORE_LIB_H */
